# Generated by Django 6.0.3 on 2026-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cold_lead', 'Cold Lead'), ('warm_lead', 'Warm Lead'), ('discovery_call', 'Discovery Call'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='cold_lead', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, help_text='Revenue or employee count', max_length=200)),
                ('funding_stage', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=200)),
                ('last_funding_date', models.DateField(blank=True, null=True)),
                ('hq_location', models.CharField(blank=True, max_length=200, verbose_name='HQ Location')),
                ('agency_relationships', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cold_lead', 'Cold Lead'), ('warm_lead', 'Warm Lead'), ('discovery_call', 'Discovery Call'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='cold_lead', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Role / Title')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, choices=[('referral', 'Referral'), ('inbound', 'Inbound'), ('event', 'Event'), ('cold_research', 'Cold Research')], max_length=20)),
                ('relationship_owner', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_needed', models.CharField(blank=True, choices=[('branding', 'Branding'), ('site', 'Website'), ('gtm', 'GTM Strategy'), ('packaging', 'Packaging'), ('social', 'Social Media'), ('email', 'Email Marketing'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('proposal', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospect', max_length=20)),
                ('probability', models.PositiveIntegerField(default=0, help_text='0–100%')),
                ('expected_timeline', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-estimated_value'],
            },
        ),
    ]
