# Generated by Django 6.0.3 on 2026-03-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('touchpoint_type', models.CharField(choices=[('email', 'Email Sent'), ('call', 'Call'), ('meeting', 'Meeting'), ('event', 'Event'), ('linkedin', 'LinkedIn Interaction'), ('proposal', 'Proposal Sent'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('logged_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
