# Generated by Django 6.0.3 on 2026-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_touchpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='heat',
            field=models.CharField(choices=[('cold', 'Cold'), ('medium', 'Medium'), ('warm', 'Warm'), ('active', 'Active Client'), ('dormant', 'Dormant Client')], default='cold', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='heat_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='heat',
            field=models.CharField(choices=[('cold', 'Cold'), ('medium', 'Medium'), ('warm', 'Warm'), ('active', 'Active Client'), ('dormant', 'Dormant Client')], default='cold', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='heat_override',
            field=models.BooleanField(default=False),
        ),
    ]
