# Generated by Django 6.0.3 on 2026-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_heat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts_ideal_industry', models.IntegerField(default=15)),
                ('pts_raised_funding', models.IntegerField(default=10)),
                ('pts_product_launch', models.IntegerField(default=10)),
                ('pts_referral', models.IntegerField(default=20)),
                ('pts_email_opened', models.IntegerField(default=5)),
                ('pts_responded', models.IntegerField(default=20)),
                ('pts_meeting_booked', models.IntegerField(default=30)),
                ('thresh_cold', models.IntegerField(default=25)),
                ('thresh_medium', models.IntegerField(default=50)),
                ('thresh_warm', models.IntegerField(default=75)),
                ('ideal_industries', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Heat Settings',
                'verbose_name_plural': 'Heat Settings',
            },
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='touchpoint_type',
            field=models.CharField(choices=[('email', 'Email Sent'), ('call', 'Call'), ('meeting', 'Meeting'), ('event', 'Event'), ('linkedin', 'LinkedIn Interaction'), ('proposal', 'Proposal Sent'), ('product_launch', 'Product Launch'), ('other', 'Other')], max_length=20),
        ),
    ]
