# Generated by Django 6.0.3 on 2026-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_heat_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatsettings',
            name='resend_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='heatsettings',
            name='resend_from_email',
            field=models.CharField(blank=True, help_text='e.g. "MegaReach <you@yourdomain.com>"', max_length=200),
        ),
        migrations.AddField(
            model_name='heatsettings',
            name='resend_webhook_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
