# Generated by Django 6.0.3 on 2026-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_resend_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatsettings',
            name='apollo_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
