# Generated by Django 6.0.3 on 2026-03-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_apollo_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatsettings',
            name='outreach_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heatsettings',
            name='outreach_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heatsettings',
            name='outreach_subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
