# Generated by Django 6.0.3 on 2026-03-20 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_reply_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invited Email',
                'verbose_name_plural': 'Invited Emails',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(blank=True, help_text='e.g. "Your Name <you@yourdomain.com>"', max_length=200)),
                ('outreach_enabled', models.BooleanField(default=False)),
                ('outreach_subject', models.CharField(blank=True, max_length=500)),
                ('outreach_body', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
