# Generated by Django 6.0.3 on 2026-03-24 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

MASTER_EMAIL = 'seanconormcdonnell@gmail.com'


def create_default_workspace(apps, schema_editor):
    User                = apps.get_model('auth', 'User')
    Workspace           = apps.get_model('crm', 'Workspace')
    WorkspaceMembership = apps.get_model('crm', 'WorkspaceMembership')
    HeatSettings        = apps.get_model('crm', 'HeatSettings')
    Contact             = apps.get_model('crm', 'Contact')
    Company             = apps.get_model('crm', 'Company')
    Opportunity         = apps.get_model('crm', 'Opportunity')
    InvitedEmail        = apps.get_model('crm', 'InvitedEmail')

    master, _ = User.objects.get_or_create(
        username=MASTER_EMAIL,
        defaults={'email': MASTER_EMAIL}
    )

    ws = Workspace.objects.create(name='WVVYReach', owner=master)
    WorkspaceMembership.objects.create(workspace=ws, user=master, role='owner')

    try:
        legacy = HeatSettings.objects.get(pk=1)
        legacy.workspace = ws
        legacy.save(update_fields=['workspace'])
    except HeatSettings.DoesNotExist:
        HeatSettings.objects.create(workspace=ws)

    Contact.objects.filter(workspace__isnull=True).update(workspace=ws)
    Company.objects.filter(workspace__isnull=True).update(workspace=ws)
    Opportunity.objects.filter(workspace__isnull=True).update(workspace=ws)

    for ie in InvitedEmail.objects.exclude(email__iexact=MASTER_EMAIL):
        user_qs = User.objects.filter(username=ie.email)
        if user_qs.exists():
            user = user_qs.first()
            WorkspaceMembership.objects.get_or_create(
                workspace=ws, user=user,
                defaults={'role': 'member'}
            )


def reverse_default_workspace(apps, schema_editor):
    Workspace = apps.get_model('crm', 'Workspace')
    Workspace.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auth_and_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspace_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_companies', to='crm.workspace'),
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.workspace'),
        ),
        migrations.AddField(
            model_name='heatsettings',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_settings', to='crm.workspace'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.RunPython(create_default_workspace, reverse_default_workspace),
    ]
