# Generated by Django 6.0.3 on 2026-03-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_workspace_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_managed',
            field=models.BooleanField(default=True, help_text='Auto-reply with AI when a reply is received'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_message_id',
            field=models.CharField(blank=True, help_text='Message-ID of last outbound email (for threading)', max_length=500),
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False, help_text='Flagged — reply was NOT sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('flagged', models.BooleanField(default=False, help_text='Flagged for human review')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_thread', to='crm.contact')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
