# Generated by Django 6.0.3 on 2026-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_google_calendar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatsettings',
            name='calendar_booking_url',
            field=models.CharField(blank=True, help_text='Booking link sent by the AI in emails (e.g. Calendly, Cal.com)', max_length=1000, verbose_name='Calendar Link'),
        ),
        migrations.AlterField(
            model_name='heatsettings',
            name='outreach_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='outreach_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
