# Generated by Django 6.0.3 on 2026-04-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_training_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='drip_followups_sent',
            field=models.IntegerField(default=0, help_text='Number of drip emails sent to this contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='drip_paused',
            field=models.BooleanField(default=False, help_text='Drip sequence temporarily paused'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='drip_sequence_stopped',
            field=models.BooleanField(default=False, help_text='Drip sequence permanently stopped (replied, unsubscribed, etc.)'),
        ),
        migrations.AlterField(
            model_name='dripeditexample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dripemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heatsettings',
            name='drip_interval_days',
            field=models.IntegerField(default=3, help_text='Days between each drip email'),
        ),
        migrations.AlterField(
            model_name='heatsettings',
            name='drip_max_followups',
            field=models.IntegerField(default=5, help_text='Maximum drip emails to send per contact'),
        ),
        migrations.AlterField(
            model_name='heatsettings',
            name='drip_model_id',
            field=models.CharField(blank=True, default='', help_text='Fine-tuned OpenAI model ID. Leave blank to use Claude.', max_length=255),
        ),
    ]
