# Generated by Django 6.0.3 on 2026-04-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_email_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('apify_import', 'Apify Import & Email'), ('backup_outreach', 'Backup Outreach')], max_length=50)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('leads_total', models.IntegerField(default=0)),
                ('leads_imported', models.IntegerField(default=0)),
                ('emails_total', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('apify_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_job', to='crm.apifyrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_jobs', to='crm.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
